In [1]:
#all imports
import pandas as pd
import numpy as np
from pathlib import Path

DATA_DIR = Path(r"C:\Users\HP\OneDrive\Desktop\BPUT\CYBERGUARD\malicious_url\data\raw")

print("Dataset directory:", DATA_DIR.resolve())
print("Files found:")

for file in DATA_DIR.iterdir():
    print(file.name)

Dataset directory: C:\Users\HP\OneDrive\Desktop\BPUT\CYBERGUARD\malicious_url\data\raw
Files found:
PhiUSIIL_Phishing_URL_Dataset.csv
uci-ml-phishing-dataset.csv

In [3]:
#loading both datasets
phiusiil_path = DATA_DIR / "PhiUSIIL_Phishing_URL_Dataset.csv"
uci_path = DATA_DIR / "uci-ml-phishing-dataset.csv"

phiusiil_df = pd.read_csv(phiusiil_path)
uci_df = pd.read_csv(uci_path)

print("PhiUSIIL shape:", phiusiil_df.shape)
print("UCI shape:", uci_df.shape)

PhiUSIIL shape: (235795, 56)
UCI shape: (11055, 32)

In [4]:
#inspaecting the scheme
print("========== PHIUSIIL ==========")
print(phiusiil_df.columns.tolist())
display(phiusiil_df.head())

print("\n========== UCI ==========")
print(uci_df.columns.tolist())
display(uci_df.head())

========== PHIUSIIL ==========
['FILENAME', 'URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP', 'TLD', 'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength', 'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef', 'label']

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

========== UCI ==========
['id', 'having_IP_Address', 'URL_Length', 'Shortining_Service', 'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix', 'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length', 'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor', 'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL', 'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe', 'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank', 'Google_Index', 'Links_pointing_to_page', 'Statistical_report', 'Result']

,id,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,1,-1,1,1,1,-1,-1,-1,-1,-1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,2,1,1,1,1,1,-1,0,1,-1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,3,1,0,1,1,1,-1,-1,-1,-1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,4,1,0,1,1,1,-1,-1,-1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,5,1,0,-1,1,1,-1,1,1,-1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [5]:
#inspecting the target labels 
print("PhiUSIIL label distribution:")
print(phiusiil_df["label"].value_counts(dropna=False))

print("\nUCI target candidates:")
for col in ["Result", "result", "label", "Label", "class"]:
    if col in uci_df.columns:
        print(f"\n{col}:")
        print(uci_df[col].value_counts(dropna=False))

PhiUSIIL label distribution:
label
1    134850
0    100945
Name: count, dtype: int64

UCI target candidates:

Result:
Result
 1    6157
-1    4898
Name: count, dtype: int64

In [6]:
#inspecting the missing or dupllicates value
def inspect_dataset(df, name):
    print(f"\n===== {name} =====")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Columns with missing values:")
    print(df.isna().sum()[df.isna().sum() > 0])

inspect_dataset(phiusiil_df, "PhiUSIIL")
inspect_dataset(uci_df, "UCI")

===== PhiUSIIL =====
Rows: 235795
Columns: 56
Duplicate rows: 0
Columns with missing values:
Series([], dtype: int64)

===== UCI =====
Rows: 11055
Columns: 32
Duplicate rows: 0
Columns with missing values:
Series([], dtype: int64)

In [7]:
#inspecting the features type
print("PhiUSIIL data types:")
display(phiusiil_df.dtypes.value_counts())

print("\nUCI data types:")
display(uci_df.dtypes.value_counts())

PhiUSIIL data types:

int64      41
float64    10
str         5
Name: count, dtype: int64

UCI data types:

int64    32
Name: count, dtype: int64